### ISSUE TITLE
Trilateration expansion and implementation of Multilateration

### ISSUE THREAD

**Issue by jaworiwanow** [emergotechnologies/helium-positioning-api#58]
Trilateration code cannot yet handle results where none of the three circles have any intersection points. There is, however, an option to choose which hotspots to use (by index) and an implementation of a cycling between those may prove a solution to this potential issue. 

An extension towards multilateration is not yet recommendable, but I’ve attached an explanation of an alternative concept to deal with the issue which would require fewer dependencies, less processing and simpler algorithms, as well as provide an area estimation instead of a point estimation. 
[multilateration_proposal.pdf](https://github.com/emergotechnologies/helium-positioning-api/files/10593693/multilateration_proposal.pdf)

**Comment by hbs9** [comment]
Is this related to that issue?

> Traceback (most recent call last):
>   File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\projects\helium\helium-positioning-api\src\helium_positioning_api\__main__.py", line 85, in <module>
>     cli()
>   File "C:\projects\helium\helium-positioning-api\.venv\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\projects\helium\helium-positioning-api\.venv\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "C:\projects\helium\helium-positioning-api\.venv\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\projects\helium\helium-positioning-api\.venv\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\projects\helium\helium-positioning-api\.venv\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\projects\helium\helium-positioning-api\src\helium_positioning_api\__main__.py", line 52, in predict
>     prediction = trilateration(uuid, model="gradient_boosting")
>   File "C:\projects\helium\helium-positioning-api\src\helium_positioning_api\trilateration.py", line 47, in trilateration
>     longitudes, latitudes, distances = compile_hotspot_info(sorted_hotspots, model)
>   File "C:\projects\helium\helium-positioning-api\src\helium_positioning_api\trilateration.py", line 74, in compile_hotspot_info
>     dist = predict_distance(
>   File "C:\projects\helium\helium-positioning-api\src\helium_positioning_api\distance_prediction.py", line 21, in predict_distance
>     preprocessor = joblib.load(path + "preprocessor.joblib")
>   File "C:\projects\helium\helium-positioning-api\.venv\lib\site-packages\joblib\numpy_pickle.py", line 650, in load
>     with open(filename, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '../models/preprocessor.joblib'

**Comment by jaworiwanow** [comment]
No, the issue you're having seems to be just about the paths of the preprocessor and models for the distance estimation. 
The expansion ideas are about the implementation of handling of unlikely but possible cases as well as making use of more than three hotspots.
