### ISSUE TITLE
possibility of different console.

### ISSUE THREAD

**Issue by rampa069** [emergotechnologies/helium-positioning-api#86]
As i have more than 10 devices onboard, i had to switch to another console.

 Is there any option to use console.helium-iot.eu instead of console.hellium.com?

**Comment by simonpfeifhofer** [comment]
@rampa069 if it's possible please try to add CONSOLE_ENDPOINT=console.helium-iot.eu to your `.env` file.

Reason: 
https://github.com/emergotechnologies/helium-api-wrapper/blob/1bee9e05c69d03dc47178243605e29fe0b39cfed/src/helium_api_wrapper/endpoint.py#L172.

Please let us know if it works for you.

**Comment by rampa069** [comment]
no, tried it and get an strange error.

requests.exceptions.MissingSchema: Invalid URL 'console.helium-iot.eu/devices/d7800d30-94c8-4340-aa27-4c9bceccebe5/events?sub_category=uplink_integration_req': No scheme supplied. Perhaps you meant https://console.helium-iot.eu/devices/d7800d30-94c8-4340-aa27-4c9bceccebe5/events?sub_category=uplink_integration_req?

**Comment by simonpfeifhofer** [comment]
Sorry, schema was missing: 
`CONSOLE_ENDPOINT=https://console.helium-iot.eu`
Can you retry?

**Comment by rampa069** [comment]
also was tested this way. seems it cannot decode json. Any undocumented debug option? :-)


```
% python -m helium_positioning_api predict --uuid d7800d30-94c8-4340-aa27-4c9bceccebe5
INFO:helium_api_wrapper.devices:Getting Device Integration Events for uuid d7800d30-94c8-4340-aa27-4c9bceccebe5
Traceback (most recent call last):
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/src/helium_positioning_api/__main__.py", line 85, in <module>
    cli()
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/src/helium_positioning_api/__main__.py", line 43, in predict
    prediction = nearest_neighbor(uuid)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/src/helium_positioning_api/nearest_neighbor.py", line 22, in nearest_neighbor
    hotspots = get_integration_hotspots(uuid)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/src/helium_positioning_api/auxilary.py", line 21, in get_integration_hotspots
    integration = get_last_integration(uuid)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/helium_api_wrapper/devices.py", line 48, in get_last_integration
    events = request(
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/helium_api_wrapper/endpoint.py", line 50, in request
    res = __request_with_exponential_backoff(
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/helium_api_wrapper/endpoint.py", line 118, in __request_with_exponential_backoff
    return __handle_response(response)
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/helium_api_wrapper/endpoint.py", line 132, in __handle_response
    r = response.json()
  File "/Volumes/HDD1/HELLIUM/helium-positioning-api/.venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by simonpfeifhofer** [comment]
@rampa069 probably it's not JSON at all.
